import { Template, waitForURL } from 'e2b'

export const template = Template()
  .fromImage('node:22-slim')
  .setUser('root')
  .setWorkdir('/')
  .runCmd('apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*')
  .copy('compile_page.sh', '/compile_page.sh')
  .runCmd("sed -i 's/\\r$//' /compile_page.sh")
  .runCmd('chmod +x /compile_page.sh')
  .runCmd('mkdir -p /home/user/nextjs-app')
  .setWorkdir('/home/user/nextjs-app')
  .runCmd('npx --yes create-next-app@latest . --yes')
  .runCmd('npx --yes shadcn@2.6.3 init -t next --yes -b neutral --force')
  .runCmd('npm install tw-animate-css')
  .runCmd('npx --yes shadcn@2.6.3 add --all --yes')
  .runCmd('cp -a /home/user/nextjs-app/. /home/user/ && rm -rf /home/user/nextjs-app') 
  .setWorkdir('/home/user')
  .setUser('user')
  .setStartCmd('bash /compile_page.sh',waitForURL('http://localhost:3000', 200));